---
:questions:
- :text: Who was the first president of the USA?
:answers:
- :text: Fred Flintstone
  :correct: false
- :text: Martha Washington
  :correct: false
- :text: George Washington
  :correct: true
- :text: George Jetson
  :correct: false
:style: radio
