---
:questions:
- :text: What color is the sky?
- :text: What's in the ocean?
- :text: What's Brent's last name?
- :text: Where is Brendan from?
:answers:
- :text: blue
- :text: salt
- :text: Van Minnen
- :text: Sydney
:style: drag
