# Root keys are locale codes as strings.
# Values can either be the string name of another locale or a map.
#
# String values are used to expand languages to include a default region.
#
# Map values can have the following keys
#   english: Name of language in English.
#   native: Name of language in the language itself.
#   fallback: Specifies a Rails-level I18n fallback.
#   debug: Causes a language to not show up in the production environment.

de: "de-DE"
de-DE:
  english: "German"
  native: "Deutsch"

el: "el-GR"
el-GR:
  english: "Greek"
  native: "ελληνικά"

en: "en-US"
en-US:
  english: "English"
  native: "English"
en-PLOC:
  english: "Pseudoloc"
  native: "Pseudoloc"
  debug: true

es: "es-ES"
es-ES:
  english: "Spanish"
  native: "Español"

fr-FR:
  english: "French"
  native: "Français"

it-IT:
  english: "Italian"
  native: "Italiano"

nl-NL:
  english: "Dutch"
  native: "Nederlands"

pt-BR:
  english: "Portuguese"
  native: "Português"

ro: "ro-RO"
ro-RO:
  english: "Romanian"
  native: "Română"

sv: 'sv-SE'
sv-SE:
  english: "Swedish"
  native: "Svenska"

vi: "vi-VN"
vi-VN:
  english: "Vietnamese"
  native: "Tiếng Việt"
  debug: true

zh: "zh-TW"
zh-TW:
  english: "Chinese"
  native: "正體字"
  debug: true
