# Root keys are locale codes as strings.
# Values can either be the string name of another locale or a map.
#
# String values are used to expand languages to include a default region.
#
# Map values can have the following keys
#   english: Name of language in English.
#   native: Name of language in the language itself.
#   fallback: Specifies a Rails-level I18n fallback.
#   debug: Causes a language to not show up in the production environment.

"af": "af-ZA"
"af-ZA":
  english: "Afrikaans"
  native: "Afrikaans"
  debug: true

"ar": "ar-SA"
"ar-SA":
  english: "Arabic"
  native: "العربية"
  debug: true
  dir: 'rtl'

"az": "az-AZ"
"az-AZ":
  english: "Azerbaijani"
  native: "azərbaycan dili"
  debug: true

"bn": "bn-BD"
"bn-BD":
  english: "Bengali"
  native: "বাংলা"
  debug: true

"ca": "ca-ES"
"ca-ES":
  english: "Catalan"
  native: "català"
  debug: true

"cs": "cs-CZ"
"cs-CZ":
  english: "Czech"
  native: "čeština"
  debug: true

"da": "da-DK"
"da-DK":
  english: "Danish"
  native: "dansk"
  debug: true

"de": "de-DE"
"de-DE":
  english: "German"
  native: "Deutsch"

"el": "el-GR"
"el-GR":
  english: "Greek"
  native: "ελληνικά"

"en": "en-US"
"en-US":
  english: "English"
  native: "English"
  fallback: "en" # Need this because source files use "en", not "en-US"
"en-PLOC":
  english: "Pseudoloc"
  native: "Pseudoloc"
  debug: true

"es": "es-ES"
"es-ES":
  english: "Spanish"
  native: "español"

"fa": "fa-IR"
"fa-IR":
  english: "Persian"
  native: "فارسی"
  debug: true
  dir: 'rtl'

"fi": "fi-FI"
"fi-FI":
  english: "Finnish"
  native: "suomi"
  debug: true

"fil": "fil-PH"
"fil-PH":
  english: "Filipino"
  native: "Pilipino"
  debug: true

"fr-FR":
  english: "French"
  native: "français"

"he": "he-IL"
"he-IL":
  english: "Hebrew"
  native: "עברית"
  debug: true
  dir: 'rtl'

"hi": "hi-IN"
"hi-IN":
  english: "Hindi"
  native: "हिन्दी, हिंदी"
  debug: true

"hu": "hu-HU"
"hu-HU":
  english: "Hungarian"
  native: "magyar"
  debug: true

"id": "id-ID"
"id-ID":
  english: "Indonesian"
  native: "Bahasa Indonesia"
  debug: true

"is": "is-IS"
"is-IS":
  english: "Icelandic"
  native: "Íslenska"
  debug: true

"it-IT":
  english: "Italian"
  native: "Italiano"

"ja": "ja-JP"
"ja-JP":
  english: "Japanese"
  native: "日本語"
  debug: true

"ko": "ko-KR"
"ko-KR":
  english: "Korean"
  native: "한국어"
  debug: true

"ms": "ms-MY"
"ms-MY":
  english: "Malay"
  native: "بهاس ملايو"
  debug: true

"my": "my-MM"
"my-MM":
  english: "Burmese"
  native: "ဗမာစာ"
  debug: true

"nl-NL":
  english: "Dutch"
  native: "Nederlands"

"no": "no-NO"
"no-NO":
  english: "Norwegian"
  native: "Norsk"
  debug: true

"pl": "pl-PL"
"pl-PL":
  english: "Polish"
  native: "język polski"
  debug: true

"pt-BR":
  #TODO: When pt-PT is turned on, indicate Brazil in names.
  english: "Portuguese"
  native: "Português"

"pt": "pt-PT"
"pt-PT":
  english: "Portuguese"
  native: "Português"
  debug: true

"ro": "ro-RO"
"ro-RO":
  english: "Romanian"
  native: "Română"

"ru": "ru-RU"
"ru-RU":
  english: "Russian"
  native: "русский язык"
  debug: true

"sq": "sq-AL"
"sq-AL":
  english: "Albanian"
  native: "gjuha shqipe"
  debug: true

"sr": "sr-SP"
"sr-SP":
  english: "Serbian"
  native: "српски језик"
  debug: true

"sv": 'sv-SE'
"sv-SE":
  english: "Swedish"
  native: "Svenska"

"ta": "ta-IN"
"ta-IN":
  english: "Tamil"
  native: "தமிழ்"
  debug: true

"th": "th-TH"
"th-TH":
  english: "Thai"
  native: "ไทย"
  debug: true

"tr": "tr-TR"
"tr-TR":
  english: "Turkish"
  native: "Türkçe"
  debug: true

"uk": "uk-UA"
"uk-UA":
  english: "Ukrainian"
  native: "українська мова"
  debug: true

"ur": "ur-PK"
"ur-PK":
  english: "Urdu"
  native: "اردو"
  debug: true
  dir: 'rtl'

"vi": "vi-VN"
"vi-VN":
  english: "Vietnamese"
  native: "Tiếng Việt"
  debug: true

"zh": "zh-TW"
"zh-TW":
  english: "Chinese (Traditional)"
  native: "繁體字"
  debug: true

"zh": "zh-CN"
"zh-CN":
  english: "Chinese (Simplified)"
  native: "简体字"
  debug: true
