# Root keys are locale codes as strings.
# Values can either be the string name of another locale or a map.
#
# String values are used to expand languages to include a default region.
#
# Map values can have the following keys
#   name: localized to be recognizable to users who need to switch.
#   fallback: Specifies a Rails-level I18n fallback.
#   debug: Causes a language to not show up in the production environment.

de: "de-DE"
de-DE:
  name: "Deutsch"

el: "el-GR"
el-GR:
  name: "ελληνικά"

en: "en-US"
en-US:
  name: "English"
en-PLOC:
  name: "Pseudoloc"
  debug: true

es: "es-ES"
es-ES:
  name: "Español"

fr-FR:
  name: "Français"

it-IT:
  name: "Italiano"

nl-NL:
  name: "Nederlands"

pt-BR:
  name: "Português"

ro: "ro-RO"
ro-RO:
  name: "Română"

sv: 'sv-SE'
sv-SE:
  name: "Svenska"

vi: "vi-VN"
vi-VN:
  name: "Tiếng Việt"
  debug: true

zh: "zh-TW"
zh-TW:
  name: "正體字"
  debug: true
